name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.3
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  internet_connection_checker: ^3.0.1
  internet_connection_checker_plus: ^2.7.2
  mailto: ^2.0.0
  shared_preferences: ^2.5.3
  split_view: ^3.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/social/
    - assets/images/project/
